// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyjdrohnuvcktiblgbex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5amRyb2hudXZja3RpYmxnYmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MzQxNTYsImV4cCI6MjA1NzIxMDE1Nn0.y2vQuJrXno2udL70duYIqbl8S12xGHWIiDOuxDPvrhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);